### ISSUE TITLE
raise NotImplementedError( NotImplementedError: You are already within an autowrap context and we currently do not supported nested autowrap.

### ISSUE THREAD

**Issue by LamOne1** [Lightning-AI/lit-parrot#154]
Hi,

I'm running the new pretrain code as it is, and I encountered this error:

```
Traceback (most recent call last):
  File ".../LLM/lit-parrot_16_06/pretrain/redpajama.py", line 317, in <module>
    CLI(setup)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File ".../LLM/lit-parrot_16_06/pretrain/redpajama.py", line 81, in setup
    fabric.launch(main, devices, train_data_dir, val_data_dir)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 732, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 814, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 823, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File ".../LLM/lit-parrot_16_06/pretrain/redpajama.py", line 110, in main
    with fabric.init_module():
  File ".../.conda/envs/parrot/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/fabric.py", line 640, in init_module
    with self._strategy.module_init_context(empty_init=empty_init):
  File ".../.conda/envs/parrot/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/strategies/fsdp.py", line 280, in module_init_context
    with empty_init_context, self.precision.init_context(), self.module_sharded_context():
  File ".../.conda/envs/parrot/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/lightning-2.1.0.dev0-py3.9.egg/lightning/fabric/strategies/fsdp.py", line 288, in module_sharded_context
    with enable_wrap(
  File ".../.conda/envs/parrot/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/torch/distributed/fsdp/wrap.py", line 264, in enable_wrap
    with _ConfigAutoWrap(**kwargs):
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/torch/distributed/fsdp/wrap.py", line 428, in __enter__
    self.enable_autowrap_context(self.kwargs)
  File ".../.conda/envs/parrot/lib/python3.9/site-packages/torch/distributed/fsdp/wrap.py", line 408, in enable_autowrap_context
    raise NotImplementedError(
NotImplementedError: You are already within an autowrap context and we currently do not supported nested autowrap.
```
I was able to run the previous release without any problem.

**Comment by carmocca** [comment]
Hi! I'm fixing this with https://github.com/Lightning-AI/lightning/pull/17832. It will land today
