### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/stabilityai/stablelm-base-alpha-3b/lit_config.json'

### ISSUE THREAD

**Issue by Keiku** [Lightning-AI/lit-parrot#158]
Sorry for the newbie question. I get the following error, what should I do?

```bash
docker@nnomayd7h7:~/lit-parrot$ python scripts/prepare_alpaca.py
/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/home/docker/lit-parrot/scripts/prepare_alpaca.py", line 169, in <module>
    CLI(prepare)
  File "/home/docker/.local/lib/python3.9/site-packages/jsonargparse/cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/home/docker/.local/lib/python3.9/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/docker/lit-parrot/scripts/prepare_alpaca.py", line 43, in prepare
    with open(checkpoint_dir / "lit_config.json", "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/stabilityai/stablelm-base-alpha-3b/lit_config.json'
docker@nnomayd7h7:~/lit-parrot$ 
```

**Comment by Keiku** [comment]
I probably solved it below.

```bash
pip install --upgrade huggingface_hub
python3 scripts/download.py --repo_id stabilityai/stablelm-base-alpha-3b
```

**Comment by carmocca** [comment]
You are missing `python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b`

This is described in https://github.com/Lightning-AI/lit-parrot/blob/main/howto/download_stablelm.md

Hope that helped!

**Comment by Keiku** [comment]
@carmocca Thank you for your kind support. In summary, I think that the preparations up to fine tune are completed with the following command.

Also, I encountered an error in fine tune. I will investigate this separately.

```bash
# install
pip install --index-url https://download.pytorch.org/whl/nightly/cu117 --pre 'torch>=2.1.0dev'
pip install -r requirements.txt
pip install --upgrade huggingface_hub
# download checkpoints
python3 scripts/download.py --repo_id stabilityai/stablelm-base-alpha-3b
# convert checkpoints
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b
# prepare tuning dataset
python scripts/prepare_alpaca.py
# Adapter
python finetune/adapter.py (I encountered an error in fine tune. i am investigating.)
```
